version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
      # Use your Dockerfile to build the app image
      build:
        context: .           # path to backend folder (where Dockerfile lives)
        dockerfile: Dockerfile
      ports:
        - "4000:4000"
      env_file:
        - .env               # uses DATABASE_URL, REDIS_URL, PORT, etc.
      depends_on:
        db:
          condition: service_healthy
      # For dev hot-reload (optional): mount code + run start:dev
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
        - /usr/src/app/prisma
        - /usr/src/app/prisma/migrations
      command: >
        sh -c "
          npx prisma generate &&
          npx prisma migrate reset --force &&
          npx prisma migrate dev --name init &&
          npm run start:dev
        "
 

volumes:
  dbdata:
